name: learn-github-actions
run-name: say hello on main
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./sayhello.sh
      - shell: bash
        env:
          FOO: bar
        run: |
          printenv | sort
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.NON_EXISTS_SECRET }}
        run: |
          echo "<$SUPER_SECRET>" | sed 's/\([a-zA-Z]\)/\1 /g'