name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          echo foo
          echo bar
      - shell: bash
        run: >
          echo hello
          echo world