name: learn-github-actions
run-name: say hello on main
on:
  push:
    branches:
      - main
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./sayhello.sh
