name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - shell: bash
        run: |
          echo ${{ matrix.version }}
          echo ${{ matrix.os }}