name: Java CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - shell: bash
        run: |
          echo ${{ matrix.version }}
          echo ${{ matrix.os }}